### ISSUE TITLE
EntityTransactionFilter should allow multiple open transactions

### ISSUE THREAD

**Issue by ebariaux** [openremote/Object-Model#2]
The current implementation shares the same EntityManager for all requests.
This prevents multiple transactions to be opened at the same time.

The EntityManagerFactory should be shared but each request should use its dedicated EntityManager.

**Comment by christianbauer** [comment]
I'll say :)

**Comment by ebariaux** [comment]
Don’t even get me started, this is another legacy from Juha, can’t understand how he coded that.

Unless I don’t understand something, the JPA EntityManager should not be shared amongst requests.

On 09 Nov 2015, at 17:27, Christian Bauer <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll say :)
